# Generated by Django 2.0 on 2017-12-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='FaceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('face_encoding_json', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='detected_faces/', verbose_name='img')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='faces',
            field=models.ManyToManyField(to='fdr_backend.FaceEntry'),
        ),
    ]
