# Generated by Django 2.0 on 2017-12-24 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fdr_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('face_encoding_json', models.TextField()),
                ('image', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.RemoveField(
            model_name='faceentry',
            name='face_encoding_json',
        ),
        migrations.RemoveField(
            model_name='faceentry',
            name='uuid',
        ),
        migrations.AddField(
            model_name='faceentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date detected'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faceentry',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='faceentry',
            name='face',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fdr_backend.Face'),
            preserve_default=False,
        ),
    ]
