# Generated by Django 2.0 on 2017-12-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdr_backend', '0002_auto_20171224_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='faces',
        ),
        migrations.AlterModelOptions(
            name='faceentry',
            options={'ordering': ('timestamp',)},
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
